# Generated by Django 3.2.16 on 2023-07-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('photo', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
