# Generated by Django 5.0.1 on 2025-02-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_gallery_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Landscapes', 'Landscapes'), ('Texture', 'Texture')], default='General', max_length=256),
        ),
    ]
