# Generated by Django 3.2.16 on 2023-07-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_sidebarinfo_youtubelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarinfo',
            name='youtubeLink',
            field=models.CharField(default='...', max_length=100),
        ),
    ]
