# Generated by Django 3.2.16 on 2023-07-18 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_sidebarinfo_youtubelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebarinfo',
            name='youtubeLink',
        ),
    ]
