# Generated by Django 3.2.16 on 2023-07-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_sidebarinfo_youtubelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatido',
            name='info',
            field=models.CharField(default='yeah, nothing to say here...', max_length=80),
        ),
    ]
