# Generated by Django 3.2.16 on 2023-07-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_whatido_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatido',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
