# Generated by Django 3.2.16 on 2023-07-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startDate', models.IntegerField()),
                ('endDate', models.IntegerField()),
                ('about', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='universityAndEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniName', models.CharField(max_length=100)),
                ('startDate', models.IntegerField()),
                ('endDate', models.IntegerField()),
                ('about', models.CharField(max_length=250)),
            ],
        ),
    ]
