# Generated by Django 3.2.16 on 2023-07-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20230717_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='endDate',
            field=models.DateField(verbose_name='ending time(blank for still going)'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='startDate',
            field=models.DateField(verbose_name='starting time'),
        ),
    ]
