# Generated by Django 3.2.16 on 2023-07-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20230718_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='endDate',
            field=models.DateField(blank=True, null=True, verbose_name='ending time(blank for still going)'),
        ),
        migrations.AlterField(
            model_name='universityandeducation',
            name='endDate',
            field=models.DateField(blank=True, null=True, verbose_name='ending time(blank for still going)'),
        ),
    ]
